### ISSUE TITLE
How to control camera via telnet?

### ISSUE THREAD

**Issue by funivan** [telmomarques/xiaomi-360-1080p-hacks#10] opened 2019-05-01 17:33 UTC
Thanks for the hack. All works fine.  I downgrade the firmware and install this hack. Then successfully login via telnet.

Here is my question: how can I turn the camera to the right or left from the telnet? Or execute other commands, for example, enable sleep mode. Thanks.

**Comment by telmomarques** [comment] 2019-05-02 07:22
Hi, unfortunately I didn't have time to look at that, yet.
There might be some way of accessing the GPIO directly, not sure.

**Comment by CleverNamesTaken** [comment] 2019-06-04 00:58
I want to spend some more time looking at the GPIO, but uh... you can turn on and off the LED by controlling the content of /sys/class/gpio/gpio78/value
OFF
echo 0 > /sys/class/gpio/gpio78/value
ON
echo 1 > /sys/class/gpio/gpio78/value

I want to try to take a look at actually controlling the direction of the camera, but I need to find some time to investigate.

**Comment by telmomarques** [comment] 2019-06-04 20:11
Nice work @CleverNamesTaken , thank you for the share!

**Comment by Jialn** [comment] 2019-12-18 11:14
Thanks for the share. Is there any more progress now?

**Comment by telmomarques** [comment] 2020-02-24 16:57
Duplicate of #21.
@Jialn please see that issue, someone has made progress.

**Closed by telmomarques** 2020-02-24 16:57 UTC

**Comment by thewh1teagle** [comment] 2020-05-22 23:16
> I want to spend some more time looking at the GPIO, but uh... you can turn on and off the LED by controlling the content of /sys/class/gpio/gpio78/value
> OFF
> echo 0 > /sys/class/gpio/gpio78/value
> ON
> echo 1 > /sys/class/gpio/gpio78/value
> 
> I want to try to take a look at actually controlling the direction of the camera, but I need to find some time to investigate.

Just want to update that you can control every led. 

for yellow led:

ON : 
```
echo 1 > /sys/class/gpio/gpio36
```
OFF:
 ```
echo 0 > /sys/class/gpio/gpio36
```


for blue led:

ON : 
```
echo 1 > /sys/class/gpio/gpio78
```
OFF:
 ```
echo 0 > /sys/class/gpio/gpio78
```
