### ISSUE TITLE
Any plans to support MJSXJ05CM?

### ISSUE THREAD

**Issue by incode4it** [telmomarques/xiaomi-360-1080p-hacks#30] opened 2020-05-23 20:06 UTC
Any plans to support MJSXJ05CM?

**Comment by ping-localhost** [comment] 2020-05-23 20:24
Duplicate of issue https://github.com/telmomarques/xiaomi-360-1080p-hacks/issues/18.

**Closed** 2020-05-23 22:01 UTC
